services:
  - type: web
    name: ide-mentor-bot-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
